name 'jenkins_dockerized'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jenkins_dockerized'
long_description 'Installs/Configures jenkins_dockerized'
version '0.1.1'
depends 'docker', '~> 0.1.1'
