name 'souls4society'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures souls4society'
long_description 'Installs/Configures souls4society'
version '0.1.0'
