node.default['souls4society']['app_name']='souls4society'
node.default['souls4society']['user_home']='/home/kd'
node.default['souls4society']['repository']='https://github.com/souls4society/souls4society.git'
node.default['souls4society']['revision']='develop'
node.default['souls4society']['com']='/var/www/souls4society.com/public_html'
node.default['souls4society']['org']='/var/www/souls4society.org/public_html'
node.default['souls4society']['info']='/var/www/souls4society.info/public_html'
node.default['souls4society']['net']='/var/www/souls4society.net/public_html'
