name 'docker'
maintainer 'kd'
maintainer_email 'kuldeeparyadotcom@gmail.com'
license 'all_rights'
description 'Installs/Configures docker'
long_description 'Installs/Configures docker'
version '0.1.1'
