name             'priority_user'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures priority_user'
long_description 'Installs/Configures priority_user'
version          '0.1.0'
